name: Crawler

on:
  schedule:
    - cron: "0 0 1 * *" # Every month on the 1st
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run crawler
        run: python crawler.py

      - name: Commit changes
        run: |
          git config user.name "Bot"
          git config user.email "bot@github.com"
          git add telebot_docs/
          git diff --staged --quiet || git commit -m "Update docs"
          git push
